const HomeProduct=
[
    {
        id: 1,
        title:"Apple iPhone 14 Pro Max(128 GB)-Gold",
        cat:"iphone",
        price:'127999',
        img:'./img/iphone14.webp',
        screensize:'6.7 inch',
        ram:'not available',
        rom:'128GB',
        frontcamra:'12MP',
        rearcamra:'48MP + 12MP + 12MP',
        operatingsystem:'iOS 16',
        sim:'Dual sim(Nano +eSim)',
        sensor:'Face ID,LiDAR Scanner,Barometer,Proximity Sensor',
        colors:'Gold',
        battery:'not available',

    },
    {
        id: 2,
        title:"Samsung Galaxy S23 Ultra 5G (Green,256GB Storage)",
        cat:"samsung",
        price:'124999',
        img:'./img/samsungs23.webp',
        screensize:'6.8 inch',
        ram:'12GB',
        rom:'256GB',
        frontcamra:'200MP + 10MP + 12MP + 10MP',
        rearcamra:'12MP',
        operatingsystem:'Android 13',
        sim:'Dual/single',
        sensor:'Fingerprint,Light sensor,Proximity sensor,Geomagnetic Sensor',
        colors:'Green',
        battery:'5000 mAh Lithium ion Battery',

    },
    {
        id: 3,
        title:"Redmi Note 12 5G (Blue,6GB,128GB Storage)",
        cat:"redmi",
        price:'18999',
        img:'./img/redminote12.webp',
        screensize:'6.67 inch',
        ram:'6GB',
        rom:'128GB',
        frontcamra:'13MP',
        rearcamra:'48MP + 8MP + 2MP',
        operatingsystem:'Android 13',
        sim:'Dual',
        sensor:'Proximity Sensor,Side FingerPrint Sensor',
        colors:'Blue',
        battery:'5000 mAh Lithium Battery',

    },
    {
        id: 4,
        title:"Vivo Y56 5G (Black 8Gb,128Gb storage)",
        cat:"vivo",
        price:'19999',
        img:'./img/vivoy56.webp',
        screensize:'6.58 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'16MP',
        rearcamra:'50MP + 2MP',
        operatingsystem:'Android 13',
        sim:'Dual Sim Dual standby',
        sensor:'E-Compass, Light sensor,Proximity sensor,Fingerprint',
        colors:'Black',
        battery:'5000 mAh Lithium Battery',

    },
    {
        id: 5,
        title:"Vivo Y100 5G (Blue,8GB,128GB Storage) ",
        cat:"vivo",
        price:'23999',
        img:'./img/vivoy100.webp',
        screensize:'6.38 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'16MP',
        rearcamra:'64MP + 2MP + 2MP',
        operatingsystem:'',
        sim:'Dual Sim',
        sensor:'E-Compass, Light sensor,Proximity sensor,Fingerprint',
        colors:'pacific Blue',
        battery:'4500 mAh Lithium Battery',

    },
    {
        id: 6,
        title:"Vivo v25 5G (Surfing Blue ,8GB,128GB)",
        cat:"vivo",
        price:'26880',
        img:'./img/vivov25.webp',
        screensize:'6.44 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'50MP',
        rearcamra:'64MP + 8MP + 2MP',
        operatingsystem:'Android 12',
        sim:'Dual Sim',
        sensor:'E-Compass, Light sensor,Proximity sensor,Fingerprint',
        colors:'Blue',
        battery:'4500 mAh Lithium Battery',

    },
    {
        id: 7,
        title:"Vivo V23 pro 5G (Gold,8GB,128GB Storage)",
        cat:"vivo",
        price:'31945',
        img:'./img/vivov23.webp',
        screensize:'6.44 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'8MP Dual Front Camra',
        rearcamra:'64MP + 8MP + 2MP',
        operatingsystem:'Android 12',
        sim:'Dual Sim',
        sensor:'E-Compass, Light sensor,Proximity sensor,Fingerprint',
        colors:'Gold',
        battery:'4200 mAh Lithium Battery',

    },
    {
        id: 8,
        title:"Redmi Note 11s (Black,6GB,64GB storage)",
        cat:"redmi",
        price:'16499',
        img:'./img/redminote11s.webp',
        screensize:'6.43 inch',
        ram:'6GB',
        rom:'64GB',
        frontcamra:'16MP',
        rearcamra:'108MP',
        operatingsystem:'Android Q 11',
        sim:'Dual Sim',
        sensor:'FingerPrint,Face Detection,',
        colors:'Black',
        battery:'5000 mAh',

    },
]
export default HomeProduct;