const ProductDetails=
[
    {
        id: 1,
        title:"Apple iPhone 14 Pro Max(128 GB)-Gold",
        cat:"iphone",
        price:'127999',
        img:'./img/iphone14.webp',
        screensize:'6.7 inch',
        ram:'not available',
        rom:'128GB',
        frontcamra:'12MP',
        rearcamra:'48MP + 12MP + 12MP',
        operatingsystem:'iOS 16',
        sim:'Dual sim(Nano +eSim)',
        sensor:'Face ID,LiDAR Scanner,Barometer,Proximity Sensor',
        colors:'Gold',
        battery:'not available',

    },
    {
        id: 2,
        title:"Samsung Galaxy S23 Ultra 5G (Green,256GB Storage)",
        cat:"samsung",
        price:'124999',
        img:'./img/samsungs23.webp',
        screensize:'6.8 inch',
        ram:'12GB',
        rom:'256GB',
        frontcamra:'200MP + 10MP + 12MP + 10MP',
        rearcamra:'12MP',
        operatingsystem:'Android 13',
        sim:'Dual/single',
        sensor:'Fingerprint,Light sensor,Proximity sensor,Geomagnetic Sensor',
        colors:'Green',
        battery:'5000 mAh Lithium ion Battery',

    },
    {
        id: 3,
        title:"Redmi Note 12 5G (Blue,6GB,128GB Storage)",
        cat:"redmi",
        price:'18999',
        img:'./img/redminote12.webp',
        screensize:'6.67 inch',
        ram:'6GB',
        rom:'128GB',
        frontcamra:'13MP',
        rearcamra:'48MP + 8MP + 2MP',
        operatingsystem:'Android 13',
        sim:'Dual',
        sensor:'Proximity Sensor,Side FingerPrint Sensor',
        colors:'Blue',
        battery:'5000 mAh Lithium Battery',

    },
    {
        id: 4,
        title:"Vivo Y56 5G (Black 8Gb,128Gb storage)",
        cat:"vivo",
        price:'19999',
        img:'./img/vivoy56.webp',
        screensize:'6.58 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'16MP',
        rearcamra:'50MP + 2MP',
        operatingsystem:'Android 13',
        sim:'Dual Sim Dual standby',
        sensor:'E-Compass, Light sensor,Proximity sensor,Fingerprint',
        colors:'Black',
        battery:'5000 mAh Lithium Battery',

    },
    {
        id: 5,
        title:"Vivo Y100 5G (Blue,8GB,128GB Storage) ",
        cat:"vivo",
        price:'23999',
        img:'./img/vivoy100.webp',
        screensize:'6.38 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'16MP',
        rearcamra:'64MP + 2MP + 2MP',
        operatingsystem:'',
        sim:'Dual Sim',
        sensor:'E-Compass, Light sensor,Proximity sensor,Fingerprint',
        colors:'pacific Blue',
        battery:'4500 mAh Lithium Battery',

    },
    {
        id: 6,
        title:"Vivo v25 5G (Surfing Blue ,8GB,128GB)",
        cat:"vivo",
        price:'26880',
        img:'./img/vivov25.webp',
        screensize:'6.44 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'50MP',
        rearcamra:'64MP + 8MP + 2MP',
        operatingsystem:'Android 12',
        sim:'Dual Sim',
        sensor:'E-Compass, Light sensor,Proximity sensor,Fingerprint',
        colors:'Blue',
        battery:'4500 mAh Lithium Battery',

    },
    {
        id: 7,
        title:"Vivo V23 pro 5G (Gold,8GB,128GB Storage)",
        cat:"vivo",
        price:'31945',
        img:'./img/vivov23.webp',
        screensize:'6.44 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'8MP Dual Front Camra',
        rearcamra:'64MP + 8MP + 2MP',
        operatingsystem:'Android 12',
        sim:'Dual Sim',
        sensor:'E-Compass, Light sensor,Proximity sensor,Fingerprint',
        colors:'Gold',
        battery:'4200 mAh Lithium Battery',

    },
    {
        id: 8,
        title:"Redmi Note 11s (Black,6GB,64GB storage)",
        cat:"redmi",
        price:'16499',
        img:'./img/redminote11s.webp',
        screensize:'6.43 inch',
        ram:'6GB',
        rom:'64GB',
        frontcamra:'16MP',
        rearcamra:'108MP',
        operatingsystem:'Android Q 11',
        sim:'Dual Sim',
        sensor:'FingerPrint,Face Detection,',
        colors:'Black',
        battery:'5000 mAh',

    },
    {
        id: 9,
        title:"Redmi 10 Power (Black,8GB,128GB storage)",
        cat:"redmi",
        price:'12499',
        img:'./img/redmi10power.webp',
        screensize:'',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'16 MP',
        rearcamra:'50MP Rear camra',
        operatingsystem:'Andriod 13',
        sim:'Dual Sim',
        sensor:'FaceId detection, FingerPrint,E-compass',
        colors:'Black',
        battery:'6000 mAh lithium ion Battery',

    },
    {
        id: 10,
        title:"Redmi 12C (Purple,6GB,128GB Storage)",
        cat:"redmi",
        price:'10499',
        img:'./img/redmi12c.webp',
        screensize:'',
        ram:'',
        rom:'',
        frontcamra:'16 MP',
        rearcamra:'',
        operatingsystem:'Android MIUI 13,Android 12.0',
        sim:'Dual Sim',
        sensor:'FingerPrint Touch,Light sensor,Face Sensor',
        colors:'Purple',
        battery:'5000 mAh Lithium ion Battery',

    },
    {
        id: 11,
        title:"Vivo Y02t (Grey,4GB,64GB Storage",
        cat:"vivo",
        price:'9999',
        img:'./img/vivoy02t.webp',
        screensize:'6.51 inch',
        ram:'4GB',
        rom:'64GB',
        frontcamra:'5MP',
        rearcamra:'8MP',
        operatingsystem:'Android 13',
        sim:'Dual sim',
        sensor:'E-compass, Light Sensor,Proximity Sensor',
        colors:'Grey',
        battery:'5000 mAh',

    },
    {
        id: 12,
        title:"Vivo Y22 (Blue,6GB,128GB storage)",
        cat:"vivo",
        price:'15499',
        img:'./img/vivoy22.webp',
        screensize:'6.55 inch',
        ram:'4GB',
        rom:'128GB',
        frontcamra:'8MP',
        rearcamra:'50MP + 2MP',
        operatingsystem:'Android 12',
        sim:'Dual sim',
        sensor:'E-compass, Virtual Gyroscope,Fingerprint Sensor',
        colors:'Blue',
        battery:'5000 mAh',

    },
    {
        id: 13,
        title:"realme narzo 60 5G (Black,8Gb+128GB)",
        cat:"realme",
        price:'23999',
        img:'./img/realmenargo60.webp',
        screensize:'6.7 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'32MP',
        rearcamra:'100MP OiS Prolight camra',
        operatingsystem:'Android 13.0',
        sim:'Dual type',
        sensor:'E-compass, Virtual Gyroscope,Fingerprint Sensor',
        colors:'Black',
        battery:'5000 mAh',

    },
    {
        id:14 ,
        title:"Apple iphone 14 (128GB)-Blue",
        cat:"iphone",
        price:'66999',
        img:'./img/iphone14s.webp',
        screensize:'6.1 inch',
        ram:'not Available',
        rom:'128GB',
        frontcamra:'12MP',
        rearcamra:'12MP + 12MP',
        operatingsystem:'iOS 16',
        sim:'Dual sim',
        sensor:'Face Id, Barometer,Dual Ambient Light Sensors',
        colors:'Blue',
        battery:'not available',

    },
    {
        id:15,
        title:"Apple iPhone 11 (64GB)-White",
        cat:"iphone",
        price:'41990',
        img:'./img/iphone11.webp',
        screensize:'6.1 inch',
        ram:'not available',
        rom:'64GB',
        frontcamra:'12MP',
        rearcamra:'12MP + 12MP',
        operatingsystem:'iOS 14',
        sim:'Dual sim',
        sensor:'Face Id, Barometer,Dual Ambient Light Sensors',
        colors:'White',
        battery:'not available',

    },
    {
        id:16 ,
        title:"Samsung Galaxy M34 5G(silver,6GB,128GB)",
        cat:"samsung",
        price:'21949',
        img:'./img/samsungm34.webp',
        screensize:'6.5 inch',
        ram:'6GB',
        rom:'128GB',
        frontcamra:'32Mp',
        rearcamra:'50MP',
        operatingsystem:'Android 13',
        sim:'Dual sim',
        sensor:'Face Id, Fingerprint ,Light sensor',
        colors:'Silver',
        battery:'6000 mAh',

    },
    {
        id:17 ,
        title:"Samsung Galaxy S20 5G(Mint,8GB,128GB)",
        cat:"samsung",
        price:'27600',
        img:'./img/samsungs20.webp',
        screensize:'6.5 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'12MP',
        rearcamra:'12MP',
        operatingsystem:'Android 10',
        sim:'Dual sim',
        sensor:'Face Id, Fingerprint ,Light sensor',
        colors:'Cloud Mint',
        battery:'4500 mAh',

    },
    {
        id:18 ,
        title:"Redmi 11 Prime (Black, 6GB, 128GB)",
        cat:"redmi",
        price:'10749',
        img:'./img/redmi11prime.webp',
        screensize:'6.58 inch',
        ram:'6GB',
        rom:'128GB',
        frontcamra:'8MP',
        rearcamra:'50MP + 2MP +2MP',
        operatingsystem:'Android 12',
        sim:'Dual sim',
        sensor:'Electronic Comapss, Side Fingerprint,IR Blaster,Proximity sensor',
        colors:'Black',
        battery:'5000 mAh',

    },
    {
        id:19 ,
        title:"Redmi Note 12 Pro 5G (Purple, 6GB, 128GB",
        cat:"redmi",
        price:'23999',
        img:'./img/redminote12pro.webp',
        screensize:'6.67 inch',
        ram:'6GB',
        rom:'128GB',
        frontcamra:'16MP',
        rearcamra:'50MP(OiS) +8MP +2MP',
        operatingsystem:'Android 12',
        sim:'Dual sim',
        sensor:'Electronic Comapss, Side Fingerprint,IR Blaster,Proximity sensor',
        colors:'purple',
        battery:'5000 mAh Lithium Polymer Battery',

    },
    {
        id:20 ,
        title:"realme 11 Pro 5G (Oasis Green, 8GB, 256Gb)",
        cat:"realme",
        price:'27999',
        img:'./img/realme11pro.webp',
        screensize:'',
        ram:'8GB',
        rom:'256GB',
        frontcamra:'32MP',
        rearcamra:'108MP',
        operatingsystem:'Android 13',
        sim:'Dual sim',
        sensor:'Electronic Comapss, Side Fingerprint,IR Blaster,Proximity sensor',
        colors:'Oasis Green',
        battery:'5000 mAh',

    },
    {
        id:21 ,
        title:"realme 10 Pro 5g (Blue, 6GB, 128GB)",
        cat:"realme",
        price:'18999',
        img:'./img/realme10pro.webp',
        screensize:'6.7 inch',
        ram:'6GB',
        rom:'128GB',
        frontcamra:'16Mp',
        rearcamra:'108MP + 8MP + 2MP',
        operatingsystem:'Android 13',
        sim:'Dual sim',
        sensor:'Electronic Comapss, Side Fingerprint,IR Blaster,Proximity sensor',
        colors:'Blue',
        battery:'5000 mAh',

    },
    {
        id:22,
        title:"Apple iphone 13 (Midnight,128GB)",
        cat:"iphone",
        price:'60999',
        img:'./img/iphone13.webp',
        screensize:'6.6 inch',
        ram:'not available',
        rom:'128GB',
        frontcamra:'12MP',
        rearcamra:'12MP + 12MP',
        operatingsystem:'iOS 15',
        sim:'Dual sim',
        sensor:'face id, barometer, Three-axis Gyro, Accelerometer ,Light sensor',
        colors:'Midnight balck',
        battery:'not available',

    },
    {
        id:23 ,
        title:"Samsung Galaxy F13 (waterfall Blue, 4GB, 128GB)",
        cat:"samsung",
        price:'11999',
        img:'./img/samsungf13.webp',
        screensize:'6.7 inch',
        ram:'4GB',
        rom:'128GB',
        frontcamra:'8MP',
        rearcamra:'50MP + 5MP +2MP',
        operatingsystem:'Android 12',
        sim:'Dual sim',
        sensor:'Virtual Light Sensing, Virtual Proximity sensing',
        colors:'Waterfall blue',
        battery:'6000 mAh',

    },
    {
        id:24 ,
        title:"realme C33 (Aqua Blue, 4GB, 128GB)",
        cat:"realme",
        price:'10499',
        img:'./img/realmec33.webp',
        screensize:'6.5 inch',
        ram:'4GB',
        rom:'128GB',
        frontcamra:'5MP',
        rearcamra:'50MP + 0.3MP',
        operatingsystem:'Android 13',
        sim:'Dual sim',
        sensor:'Virtual Light Sensing, Virtual Proximity sensing',
        colors:'Aqua Blue',
        battery:'5000 mAh',

    },
    {
        id:25,
        title:"realme C55 (Rainforest,8GB ,128GB)",
        cat:"realme",
        price:'13999',
        img:'./img/realmec55.webp',
        screensize:'6.72',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'8MP',
        rearcamra:'64MP + 2MP',
        operatingsystem:'Android 13',
        sim:'Dual sim',
        sensor:'Virtual Light Sensing, Virtual Proximity sensing',
        colors:'Rainy night',
        battery:'5000 mAh',

    },
    {
        id:26 ,
        title:"Apple iphone 14 Plus (Blue, 128 GB)",
        cat:"iphone",
        price:'79999',
        img:'./img/iphone14plus.webp',
        screensize:'6.7 inch',
        ram:'not available',
        rom:'128GB',
        frontcamra:'12MP',
        rearcamra:'12MP + 12MP',
        operatingsystem:'iOS 16',
        sim:'Dual sim',
        sensor:'face id, barometer, Three-axis Gyro, Accelerometer ,Light sensor',
        colors:'Blue',
        battery:'not available',

    },
    {
        id:27 ,
        title:"Apple iphone 14 Pro Max (silver,1 TB)",
        cat:"iphone",
        price:'177999',
        img:'./img/iphone14promax.webp',
        screensize:'6.6 inch',
        ram:'not available',
        rom:'1 TB ROM',
        frontcamra:'12MP',
        rearcamra:'48MP + 12MP + 12MP',
        operatingsystem:'iOS 16',
        sim:'Dual sim',
        sensor:'face id, barometer, Three-axis Gyro, Accelerometer ,Light sensor',
        colors:'Silver',
        battery:'not available',

    },
    {
        id: 28,
        title:"SAMSUNG Galaxy A34 5G (Violet ,8GB, 128GB)",
        cat:"samsung",
        price:'30999',
        img:'./img/samsunga34.webp',
        screensize:'6.6 inch',
        ram:'8GB',
        rom:'128GB',
        frontcamra:'13Mp',
        rearcamra:'48MP + 8Mp +5MP',
        operatingsystem:'Android 13',
        sim:'Dual sim',
        sensor:'Virtual Light Sensing, Virtual Proximity sensing',
        colors:'Violet',
        battery:'5000 mAh',

    },
    {
        id:29 ,
        title:"SAMSUNG Galaxy A14 5G(Dark Red, 6GB ,128GB)",
        cat:"samsung",
        price:'17999',
        img:'./img/samsunga14.webp',
        screensize:'6.7 inch',
        ram:'6GB',
        rom:'128GB',
        frontcamra:'13MP',
        rearcamra:'50MP +8MP +5MP',
        operatingsystem:'Android 13',
        sim:'Dual sim',
        sensor:'Virtual Light Sensing, Virtual Proximity sensing',
        colors:'Dark Red',
        battery:'5000 mAh',

    },
    {
        id:30 ,
        title:"realme 10 (Rush Black, 8GB, 128GB)",
        cat:"realme",
        price:'16999',
        img:'./img/realme10.webp',
        screensize:'6.4 inch',
        ram:'8GB',
        rom:'128 GB',
        frontcamra:'16MP',
        rearcamra:'50MP +2MP',
        operatingsystem:'Android 12',
        sim:'Dual sim',
        sensor:'Magnetic Induction Sensor, Light Sensor,Proximity Sensor,',
        colors:'Rush Black',
        battery:'5000 mAh',

    },
   
]
export default ProductDetails